create table EMPLOYEESALARY
(EmpID INT NOT NULL unique,
PROJECT VARCHAR(255),
SALARY INT)
SELECT * FROM EMPLOYEESALARY
INSERT INTO EMPLOYEESALARY
VALUES(121, 'P1', 8000)  
INSERT INTO EMPLOYEESALARY
VALUES(321, 'P2', 1000)  
INSERT INTO EMPLOYEESALARY
VALUES(421, 'P1', 12000)
INSERT INTO EMPLOYEESALARY
VALUES(333, 'P3', 3000)  
CREATE TABLE EMPLOYEEDETAILS
(EmpID INT NOT NULL,
FULLNAME VARCHAR(255),
MANAGERID INT,
DATEOFJOINING VARCHAR(255))
INSERT INTO NYUTA_DB.EMPLOYEEDETAILS
VALUE(121,'JOHN SNOW',321,'01/31/2014')
SELECT * FROM NYUTA_DB.EMPLOYEEDETAILS

INSERT INTO NYUTA_DB.EMPLOYEEDETAILS
VALUES(321,'WALTER WHITE',986,'01/31/2015'),
(421,'KULDEEP RANA',876,'27/11/2016'),
(555, 'HELEN TOMMY', 999, '31/12/2024')
 
1  SELECT COUNT(EmpID) FROM EMPLOYEESALARY
WHERE PROJECT='P1'
2  select FULLNAME FROM EMPLOYEEDETAILS
WHERE EmpID=(SELECT EmpID FROM EMPLOYEESALARY
WHERE SALARY BETWEEN 5000 AND 10000)
3  SELECT COUNT(EmpID), PROJECT FROM EMPLOYEESALARY
GROUP BY PROJECT
ORDER BY COUNT(EmpID) DESC
4  SELECT * FROM EMPLOYEEDETAILS
LEFT JOIN EMPLOYEESALARY
ON EMPLOYEEDETAILS.EmpID=EMPLOYEESALARY.EmpID
5  create table test(test int not null)
select * from test
 6  drop table test
 select * from test
 7  select *from EMPLOYEEDETAILS 
 WHERE DATEOFJOINING LIKE '%16'
 8  INSERT INTO EMPLOYEEDETAILS 
 VALUE(777, 'MARTIN IDEN', 888, '31/12/2025')
# SELECT * FROM EMPLOYEEDETAILS
 # SELECT * FROM EMPLOYEESALARY
9 #  UPDATE EMPLOYEESALARY SET PROJECT='P4' WHERE EmpID= 121
# ALTER TABLE EMPLOYEESALARY 
 DROP CONSTRAINT EmpID 

# ALTER TABLE EMPLOYEESALARY 
  ADD PRIMARY KEY(PROJECT)
#  show index from EMPLOYEESALARY where Key_name = 'PRIMARY'   #'FOREIGN'


 UPDATE EMPLOYEESALARY
SET SALARY=2000
WHERE PROJECT='P2'
#  ALTER TABLE EMPLOYEESALARY 
  DROP PRIMARY KEY
  # ALTER TABLE EMPLOYEESALARY
   ADD PRIMARY KEY (EmpID)
 #show index from EMPLOYEESALARY where Key_name = 'PRIMARY'
  
  10.  SELECT * FROM EMPLOYEEDETAILS 
  RIGHT JOIN EMPLOYEESALARY
  ON EMPLOYEEDETAILS.EmpID=EMPLOYEESALARY.EmpID
  
   SELECT * FROM EMPLOYEESALARY
  RIGHT JOIN EMPLOYEEDETAILS
  ON EMPLOYEESALARY.EmpID=EMPLOYEEDETAILS.EmpID
  

