SELECT * FROM ADDRESSES
SELECT *FROM USERAN
SELECT USER_ID, FULL_NAME, STREET, CITY
FROM ADDRESSES
FULL JOIN USERAN
ON ADDRESSES.USER_ID=USERAN.ID
WHERE ID=3

 ALTER TABLE ADDRESSES
 RENAME COLUMN ID TO USER_ID
 
 SELECT FULL_NAME FROM USERAN
 WHERE ID=
 (SELECT USER_ID FROM ADDRESSES
 where STREET like 'Elm street')
 
 
 
 
SELECT USER_ID, FULL_NAME, STREET, CITY
FROM ADDRESSES
JOIN USERAN
ON ADDRESSES.USER_ID=USERAN.ID
SELECT USER_ID, FULL_NAME, STREET, CITY
FROM ADDRESSES
LEFT JOIN USERAN
ON ADDRESSES.USER_ID=USERAN.ID
 
 SELECT FULL_NAME FROM USERAN
 WHERE ID=(SELECT USER_ID FROM ADDRESSES
 WHERE CITY='Boston')
 11.  select FULL_NAME FROM USERAN
 JOIN ADDRESSES
 ON USERAN.ID=ADDRESSES.USER_ID
 WHERE CITY='San Francisco'
 
 12.  select * from USERAN
 SELECT * FROM ADDRESSES
 SELECT FULL_NAME, LAST_LOGIN
 FROM USERAN
 WHERE ENABLED='F'
 13. SELECT USERAN.FULL_NAME, STREET FROM USERAN
 JOIN ADDRESSES
 ON USERAN.ID=ADDRESSES.USER_ID
 WHERE NOT STREET='3 Main street'
  
  14. 
  SELECT USERAN.FULL_NAME, ADDRESSES.STREET,CITY FROM USERAN
 JOIN ADDRESSES
 ON USERAN.ID=ADDRESSES.USER_ID
 WHERE ADDRESSES.STREET= '3 MAIN STREET' OR ADDRESSES.CITY='San Francosco'
 
 15. SELECT FULL_NAME FROM USERAN
 WHERE ID=(SELECT USER_ID FROM ADDRESSES
 WHERE CITY='Boston')
 SELECT  ID,FULL_NAME, STREET, CITY FROM USERAN
 JOIN ADDRESSES 
 ON USERAN.ID=ADDRESSES.USER_ID
 WHERE CITY="Boston" 
 
 